apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: grafana-enterprise-metrics.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An operator to install Grafana Enterprise Metrics (GEM) on OpenShift
  displayName: Grafana Enterprise Metrics (GEM) Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Grafana Enterprise Metrics
  - GEM
  - Metrics
  - Observability
  links:
  - name: Grafana Enterprise Metrics
    url: https://grafana-enterprise-metrics.domain
  maturity: alpha
  provider:
    name: Grafana Labs
    url: https://grafana.com
  version: 0.0.0
